### ISSUE TITLE
problem in EventManager

### ISSUE THREAD

**Issue by janus112** [dariocravero/padrino-websockets#5]
Hello, I think that you have a problem in EventManager, which implies a user is not removed from a channel, if the connection is closed.

Since you define on_shutdown(event) in EventManager, its not called in BaseEventManager.

I would remove it, since Faye takes care of removing the pinger, and let BaseEventManager define on_shutdown(event), that is, appending event argument.

In BaseEventManager, I guess on_shutdown(event) should call @@connections[@channel].delete(@user)

and not 

@@connections[@channel].delete(@ws)

**Comment by dariocravero** [comment]
Hi @janus112, thanks for your comment and spotting that!

Perhaps we could replace [this](https://github.com/dariocravero/padrino-websockets/blob/master/lib/padrino-websockets/faye/event-manager.rb#L19-L24) with:

```ruby
def on_shutdown(event)
  super(event)
  @pinger.cancel if @pinger
end
```

The other fix you're pointing to is correct too.

Can you verify that that #6 does it?

**Comment by janus112** [comment]
Its indeed working. Great. Ill be using this in production soon.

**Comment by dariocravero** [comment]
Merged! I'll push it to rubygems later on today. Sorry about that, even though it works, this gem clearly needs unit testing; I never got around that and I don't think it will happen anytime soon unfortunately. PRs welcome :).

**Comment by janus112** [comment]
Sounds great. No problem. Even if it was unit tested, I would review it anyway for production. Thanks

**Comment by dariocravero** [comment]
@janus112 [version released](https://rubygems.org/gems/padrino-websockets/versions/0.1.1)!
